name: Auto Commit

on:
  schedule:
    - cron: '*/12 * * * *' 

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name 'themuuln'
          git config --global user.email 'zerone.offical@gmail.com'
          git config pull.rebase false

      - name: Push Empty Commits
        run: |
          cd $GITHUB_WORKSPACE
          branch="main"

          timestamp=$(date '+%Y-%m-%d %H:%M:%S')
          commit_message="Automated empty commit at $timestamp by themuuln/auto-committer"

          git pull origin $branch --ff-only

          for i in {1..10}; do
            git commit --allow-empty -m "$commit_message"
          done

          git push origin $branch