name: Auto Commit

on:
  schedule:
    - cron: "0 */2 * * *"

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Check Day of the Week
        id: check_day
        run: echo "::set-output name=day::$(date +%u)"

      - name: Conditional Workflow Run
        if: ${{ steps.check_day.outputs.day != '6' && steps.check_day.outputs.day != '7' }}
        run: |
          git config --global user.name 'themuuln'
          git config --global user.email 'zerone.offical@gmail.com'
          git config pull.rebase false

          cd $GITHUB_WORKSPACE
          branch="main"

          timestamp=$(date '+%Y-%m-%d %H:%M:%S')

          git pull origin $branch --ff-only

          commit_count=$((RANDOM % 4 + 2))

          for ((i=1; i<=commit_count; i++)); do
            commit_prefix=("Fix" "Add Feature" "Update Documentation" "Refactor Code" "Test Changes" "Chore")
            random_prefix=${commit_prefix[$((RANDOM % ${#commit_prefix[@]}))]}
            commit_message="$random_prefix: Automated commit $i of $commit_count at $timestamp by themuuln/auto-committer"
            git commit --allow-empty -m "$commit_message"
          done

          git push origin $branch
