name: Auto Commit

on:
  schedule:
    # - cron: '0 */3 * * *' # Schedule the workflow to run every three hours
    - cron: '22 23 * * *' # Schedule the workflow to run every three hours

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config --global user.name 'themuuln'
          git config --global user.email 'zerone.offical@gmail.com'

      - name: Commit and Push
        run: |
          for i in {1..20}; do
            echo "Automatic empty commit $i" >> empty-commit.txt
            git add empty-commit.txt
            git commit -m "Automatic empty commit $i"
            git push
          done
