name: Daily Commit

on:
  schedule:
    - cron: "26 18 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git
        run: |
          git config --global user.name "themuuln"
          git config --global user.email "zerone.offical@gmail.com"

      - name: Clone the repository
        uses: actions/checkout@v2

      - name: Modify File and Commit
        run: |
          for i in {1..20}; do
            # Modify an existing file (e.g., README.md) and commit with a unique message
            echo "Updated by Daily Commit - $(date +'%Y-%m-%d %H:%M:%S')" >> README.md
            git add .
            git commit -m "Daily commit - $i/20 - $(date +'%Y-%m-%d %H:%M:%S')"
          done
          
      - name: Push Commits
        run: |
          # Push all 20 commits to the repository
          git push
          
      - name: Send Notification
        if: success()
        run: |
          # Send notification to Slack or Discord (Replace with your notification command)
          echo "Daily Commits completed successfully! 20 changes committed."          
